import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo, Inter, Playfair_Display } from "next/font/google";
import { SearchProvider } from "@/lib/contexts/search-context";
import { AuthProvider } from "@/lib/contexts/auth-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${archivo.variable} ${inter.variable} ${playfairDisplay.variable} antialiased`}
      >
        <SearchProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </SearchProvider>
      </body>
    </html>
  );
}
